# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

minimum_pre_commit_version: 2.8.0
default_stages: [ commit, push, manual ]

repos:
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v15.0.6
      hooks:
          - id: clang-format
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: mixed-line-ending
        - id: check-yaml
          args:
            - --allow-multiple-documents
        - id: check-merge-conflict
        - id: check-added-large-files
          args: [ --maxkb=800 ]
        - id: debug-statements
        - id: check-ast
        - id: fix-byte-order-marker
        - id: check-case-conflict
        - id: check-docstring-first
        - id: check-executables-have-shebangs

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
        - id: pyupgrade
          args: [ --py39-plus ]

    - repo: https://github.com/google/pre-commit-tool-hooks
      rev: v1.2.4 # Use the rev you want to point at.
      hooks:
        # In a markdown file, put the <!-- toc --> and <!-- tocstop --> markers to
        # indicate where to put the table of contents
        - id: markdown-toc

    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
        - id: black

    - repo: https://github.com/PyCQA/isort
      rev: 5.11.4
      hooks:
        - id: isort

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          args: [ "--config=setup.cfg" ]
          additional_dependencies: [ flake8-isort ]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
# https://pre-commit.ci/
ci:
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
